---
title: "hw03 Tasks 1-3"
output: github_document
---

```{r, message = F, echo = F}
library(tidyverse)
library(gapminder)
library(ggridges)
library(scales)
```

## Task 1: Get the maximum and minimum of GDP per capita for all continents

```{r,  fig.align = "right"}
gapminder %>% 
  group_by(continent) %>% # group rows into chunks by continent
  summarise(min_gdpPercap = min(gdpPercap),
            max_gdpPercap = max(gdpPercap)) %>% # collapse the continent group by finding the maximum and minimum gdpPercap values
  as_tibble() %>% # convert data into a tibble
  knitr::kable()
```

## Task 2: Look at the spread of GDP per capita within the continents

```{r, message = F}
gapminder %>% 
  ggplot(aes(gdpPercap, continent)) + # specify x and y aesthetics
  scale_x_log10(label = scales::comma_format()) + # log transform x axis and convert x labels in comma format
  ggridges::geom_density_ridges() + # add ridges layer to plot
  xlab("Log10(gdpPerCap)") # modify x axis label
```

## Task 3: Changes in life expectancy over time on different continents

```{r}
gapminder %>% 
  group_by(continent, year) %>% # group rows into chunks by continent and year
  summarise(average_lifeExp = mean(lifeExp)) %>% # collapse the groups by averaging the life expectancies across all countries per continent
  ggplot(aes(year, average_lifeExp, color = continent)) + # specify the x and y aesthetics
  geom_point() + # create points for each data point
  geom_line() + # connect the data points via a line
  ylab("Average Life Expectancy") # modify the y axis label
```

```{r, fig.width = 15}
gapminder %>% 
  ggplot(aes(year, lifeExp, color = continent, group = country)) + # specifiy x, y, color, and group aesthetics
  facet_wrap(~continent, nrow = 1) + # create multiple panels
  geom_point(alpha = 0.5) + # create data points with 50% transparency
  geom_line(alpha = 0.5) + # connect the data points via a line with 50% transparency
  theme(legend.position = "bottom") # move the legend to the bottom of the plot
```

